version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_tg_bot
    environment:
      POSTGRES_DB: tgbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: QokPO37X1SKx
    ports:
      - "5434:5432"
    volumes:
      - tgbot:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  tgbot: